services:
  - type: web
    name: phense-api
    env: python
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: OPEN_TOPO_BASE_URL
        value: https://api.opentopodata.org/v1/srtm30m
      - key: ALLOWED_ORIGINS
        value: "*"

  - type: web
    name: phense
    env: static
    buildCommand: ""
    staticPublishPath: ./static
    routes:
      - type: rewrite
        source: /assess
        destination: /assess.html
      - type: rewrite
        source: /results
        destination: /results.html
      - type: rewrite
        source: /methodology
        destination: /methodology.html
      - type: rewrite
        source: /about
        destination: /about.html


